// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Line struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Stops []*Stop `json:"stops"`
}

type Operator struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Lines []*Line `json:"lines"`
}

type Query struct {
}

type Stop struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
