// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mickey struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Todo struct {
	ID   string  `json:"id"`
	Text string  `json:"text"`
	Done bool    `json:"done"`
	User *Mickey `json:"user"`
}
